### ISSUE TITLE
Deserialization of EmbedlyObjects fail in Ruby 2.3.1

### ISSUE THREAD

**Issue by martijnbleeker** [embedly/embedly-ruby#32]
We're currently storing `EmbedlyObjects` in a database serialized to YAML.

We are in the process of upgrading to ruby 2.3.1, but on `YAML.load` we get a `ArgumentError` because apparently the initializer is called without any arguments.

This could be caused by a behavioural change of the YAML parser/loader in ruby 2.3.1.
I'm in the process of searching for a solution for this problem.

```
Failure/Error: obj = new(YAML.load(yml)) if yml.present?

     ArgumentError:
       wrong number of arguments (given 0, expected 1)
     # /Users/martijn/.gem/ruby/2.3.1/gems/embedly-1.9.1/lib/embedly/model.rb:6:in `initialize'
```

**Comment by sergey-koba-mobidev** [comment]
As workaround create initializer with this code:

class Embedly::EmbedlyObject
  def initialize
    super
  end
end
